#!/usr/bin/env python3
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def replace_once(path, old, new):
    file_path = ROOT / path
    text = file_path.read_text()
    count = text.count(old)
    if count != 1:
        raise RuntimeError(f"Expected exactly one match in {path}, found {count}")
    file_path.write_text(text.replace(old, new, 1))


practice_old = """9. on request, and at the point where a result becomes a principal claim or a workstream resumes after a pause, state the premises the current line of work depends on, identify for each whether it has been verified against an artifact or inherited from the project record, and name for each what observation would show it to be wrong.\n"""
practice_new = practice_old + """10. treat every new scientific mechanism, causal explanation, relationship, interpretation, boundary, membership, or analogous proposition as `HYPOTHESIS ONLY — not source-supported` unless and until the User promotes that exact proposition under the evidence-support rule below;\n11. allow hypothesis-only material to guide searches, analyses, model building, or experimental planning, but exclude it from claim titles, signed or accepted edges, mechanism membership, evidence counts, boundary definitions, and analogous evidence-bearing project structures;\n12. use `EVIDENCE SUPPORTED — [specific proposition]` only for the exact proposition for which evidence has been identified and verified. The record states the supporting source or artifact, what the evidence supports, what it does not support, and any material limitations. External-source evidence follows `REFERENCE-VALIDATION`; project-generated evidence is tied to the exact accepted artifact or run;\n13. promote a proposition from hypothesis-only to evidence-supported only when the User determines that the evidence meets the project-specific evidentiary threshold for that exact proposition. AI participants may identify evidence and recommend promotion but may not promote a claim themselves;\n14. never treat partial support as support for a broader claim. If evidence supports only a sub-proposition, only that sub-proposition may receive `EVIDENCE SUPPORTED`; the broader statement remains `HYPOTHESIS ONLY — not source-supported`. Preserve the hypothesis history and record the User's promotion decision.\n"""
replace_once("protocol/01.work-contract.md", practice_old, practice_new)

evidence_old = """## S3.3 Evidence classes\n\nThe protocol distinguishes proposals, evidence, file identity, and acceptance.\n\n1. Model prose is a proposal or interpretation.\n2. A sandbox run is evidence only for the recorded sandbox, code, and inputs.\n3. A commit identifies a version of a file but does not establish scientific validity.\n4. A User-run result is authoritative only for its recorded code, command, inputs, configuration, and environment.\n5. A citation is acceptable only after `REFERENCE-VALIDATION`, and a novelty claim only after `PRIOR-ART-LINEAGE`.\n6. The User decides whether the combined evidence satisfies the acceptance criteria.\n"""
evidence_new = """## S3.3 Evidence classes and claim state\n\nThe protocol distinguishes hypotheses, evidence-supported propositions, file identity, execution evidence, and User acceptance.\n\n1. Model prose is a proposal or interpretation. A newly proposed scientific proposition defaults to `HYPOTHESIS ONLY — not source-supported`.\n2. `HYPOTHESIS ONLY — not source-supported` material may be retained and used to guide exploration, but it does not enter evidence-bearing project state. It is excluded from claim titles, signed or accepted edges, mechanism membership, evidence counts, boundary definitions, and analogous evidence-bearing structures.\n3. `EVIDENCE SUPPORTED — [specific proposition]` is claim-specific. Its record identifies the exact proposition, supporting source or artifact, what the evidence supports, what it does not support, and material limitations. A generic statement that a broader mechanism or interpretation is "supported" is insufficient.\n4. Partial support does not promote a broader claim. If evidence supports only one component, that component may be proposed for promotion while the parent mechanism or statement remains `HYPOTHESIS ONLY — not source-supported`.\n5. External-source evidence is admissible only after the applicable `REFERENCE-VALIDATION`; project-generated evidence is tied to the exact run, artifact, inputs, configuration, and accepted execution record.\n6. The User defines the evidentiary threshold for each proposition and is the only participant who can promote it from hypothesis-only to evidence-supported project state. AI participants may recommend promotion but do not perform it themselves.\n7. A sandbox run is evidence only for the recorded sandbox, code, and inputs.\n8. A commit identifies a version of a file but does not establish scientific validity.\n9. A User-run result is authoritative only for its recorded code, command, inputs, configuration, and environment.\n10. Evidence support is bounded by the proposition and evidence recorded. It does not establish unsupported causal, mechanistic, boundary, membership, or generalization claims. A proposition may be returned to hypothesis-only or superseded when later evidence changes its status.\n11. A novelty claim is released only after the applicable `PRIOR-ART-LINEAGE`.\n12. The User decides whether the combined evidence satisfies the acceptance criteria and whether any proposition is promoted.\n"""
replace_once("protocol/01.work-contract.md", evidence_old, evidence_new)

skill_old = """4. **PRACTICE.** Be constructive and substantive. Check descriptions against actual artifacts before relying on them. Distinguish inherited assumptions from verified evidence. State errors and consequences directly. When a result becomes a principal claim or work resumes, identify its premises and what observations would falsify them.\n"""
skill_new = """4. **PRACTICE.** Be constructive and substantive. Check descriptions against actual artifacts before relying on them. Distinguish inherited assumptions from verified evidence. State errors and consequences directly. When a result becomes a principal claim or work resumes, identify its premises and what observations would falsify them. Default new scientific propositions to `HYPOTHESIS ONLY — not source-supported`; promotion requires claim-specific evidence and User acceptance.\n"""
replace_once("skills/scuter/SKILL.md", skill_old, skill_new)

marker = """Release requirements are evaluated under the adopted protocol. An unmet requirement remains recorded as unmet, including when the User elects to proceed and records a reason. Approval fields are positions, not votes that combine into acceptance.\n\n"""
addition = marker + """## Evidence-state discipline\n\nEvery newly proposed scientific mechanism, causal explanation, relationship, interpretation, boundary, membership, or analogous proposition defaults to `HYPOTHESIS ONLY — not source-supported`. Hypothesis-only material may guide searches, analyses, model building, or experimental planning, but it does not populate claim titles, signed or accepted edges, mechanism membership, evidence counts, boundary definitions, or analogous evidence-bearing structures.\n\nUse `EVIDENCE SUPPORTED — [specific proposition]` only for the exact proposition supported by identified and verified evidence. Record the supporting source or artifact, what the evidence supports, what it does not support, and material limitations. Partial support never promotes a broader claim: only the supported sub-proposition can be proposed for promotion, while the broader claim remains hypothesis-only.\n\nThe User defines the evidentiary threshold and is the only participant who promotes a proposition into evidence-supported project state. AI participants may identify evidence and recommend promotion, but never silently remove a hypothesis-only label or broaden an evidence-supported statement beyond the proposition the User accepted. Preserve the prior hypothesis state and the User's promotion decision in the durable record.\n\n"""
replace_once("skills/scuter/SKILL.md", marker, addition)

guide_old = """## 5. Maintain evidence and review state\n\nRecord what a reviewer inspected, the specific version, what is supported, what remains uncertain, and any required repair. Keep dated review text as the historical evidence. Review-request checkboxes route current work; approval fields record endorsement of the current version.\n\n"""
guide_new = """## 5. Maintain evidence and review state\n\nRecord what a reviewer inspected, the specific version, what is supported, what remains uncertain, and any required repair. Keep dated review text as the historical evidence. Review-request checkboxes route current work; approval fields record endorsement of the current version.\n\nTreat claim state separately from review state. Every newly proposed scientific proposition defaults to `HYPOTHESIS ONLY — not source-supported`. It may guide further work but does not enter evidence-bearing structures. Use `EVIDENCE SUPPORTED — [specific proposition]` only when the record identifies the exact supporting source or artifact, what that evidence supports, what it does not support, and its limitations. The User sets the evidentiary threshold and is the only participant who promotes a proposition.\n\nPartial support is not a middle state for the whole claim. If evidence supports one sub-proposition but not a broader mechanism, only that sub-proposition can be proposed as `EVIDENCE SUPPORTED`; the broader mechanism remains `HYPOTHESIS ONLY — not source-supported`. Apply these labels at the proposition level rather than to an entire note or log entry when it contains multiple claims. Preserve the transition and User decision in the durable record.\n\n"""
replace_once("docs/implementation-guide.md", guide_old, guide_new)

review_old = """Separate proposed interpretations from observed results. Identify sandbox evidence as such. A repository commit establishes source identity, while a run record states what executed. Neither agreement nor a successful build supplies the missing evidence for a scientific claim.\n"""
review_new = """Separate proposed interpretations from observed results. Every newly proposed scientific proposition defaults to `HYPOTHESIS ONLY — not source-supported`. Hypothesis-only material may guide further work but is excluded from evidence-bearing project structures. Use `EVIDENCE SUPPORTED — [specific proposition]` only for the exact proposition whose evidence has been identified and verified, and record what the evidence does and does not support. Partial support never promotes the broader claim. The User sets the evidentiary threshold and is the only participant who promotes a proposition. Identify sandbox evidence as such. A repository commit establishes source identity, while a run record states what executed. Neither agreement nor a successful build supplies the missing evidence for a scientific claim.\n"""
replace_once("docs/record-and-review.md", review_old, review_new)

notion_old = """Create a Project Overview, one Collaboration Log, a prior-art search record, and a citation ledger. Add numbered notebooks for longer methods and analyses as needed. The Overview states what currently governs. The log preserves material actions, evidence, decisions, and next steps.\n"""
notion_new = notion_old + """\nEvidence-state labels are proposition-specific. When an entry contains more than one scientific proposition, do not use one row-level checkbox or status to imply that all are supported. Label the exact proposition in the entry body or maintain separate claim records: `HYPOTHESIS ONLY — not source-supported` is the default, and `EVIDENCE SUPPORTED — [specific proposition]` is used only after the User accepts the evidence for that proposition.\n"""
replace_once("docs/notion-setup.md", notion_old, notion_new)

print("Evidence-state source updates applied")
