#!/usr/bin/env python3
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def replace_once(path, old, new):
    file_path = ROOT / path
    text = file_path.read_text()
    count = text.count(old)
    if count != 1:
        raise RuntimeError(f"Expected exactly one match in {path}, found {count}")
    file_path.write_text(text.replace(old, new, 1))


protocol_old = """6. An unresolved, broken, mismatched, inaccessible, or unvalidated reference blocks merge and release.\n\n## S2.4 Collaborative practice  `PRACTICE`\n"""
protocol_new = """6. An unresolved, broken, mismatched, inaccessible, or unvalidated reference blocks merge and release.\n\n### Citation requirements\n\nThe following rules determine when a scientific statement requires an external citation. Describing a statement as \"common knowledge,\" \"standard,\" \"well known,\" or similar does not by itself exempt it from citation.\n\n1. **Current-project hypothesis, assumption, derivation, or result.** An external citation is not required when the statement genuinely originates in the current project. It is clearly identified as a hypothesis, assumption, derivation, observation, or result of the present work and linked to the relevant project evidence or derivation. Any external premise on which it depends remains subject to citation.\n2. **Pure mathematical identity or explicit definition.** A citation is generally not required for an identity derived directly from mathematics or for a definition introduced explicitly by the present work. A named theorem, established method, conventional definition, or result with an identifiable scholarly origin is cited when that origin is relevant.\n3. **Claim derived from outside work.** Any empirical, theoretical, methodological, mechanistic, or interpretive claim originating outside the current project is cited to an appropriate source.\n4. **Standard scientific fact.** A scientific statement is not exempt from citation merely because it is described as standard or commonly known. If there is any plausible alternate convention, scope, interpretation, population, experimental context, or domain of validity, an appropriate source is cited.\n5. **Quantitative statement.** A numerical value, range, rate, threshold, effect size, prevalence, parameter, or other quantitative scientific statement is cited unless it is directly calculated, measured, or derived in the current work. Internally derived quantities are linked to the corresponding method, data, calculation, or result.\n6. **Novelty or priority statement.** A claim that a method, result, observation, interpretation, or resource is novel, first, unique, or previously unreported requires citation to the closest relevant prior work and the applicable recorded search under `PRIOR-ART-LINEAGE`. Citations alone do not establish absence of prior art. Cite only what is needed to support the specific comparison or priority statement rather than expanding the text into an unnecessary literature survey.\n\nWhen uncertain whether an external scientific statement requires citation, the default is to cite and validate the source rather than invoke common knowledge.\n\n## S2.4 Collaborative practice  `PRACTICE`\n"""
replace_once("protocol/01.work-contract.md", protocol_old, protocol_new)

# Fix the punctuation seam noted in prior review while this list is being edited.
replace_once(
    "protocol/01.work-contract.md",
    "9. on request, and at the point where a result becomes a principal claim or a workstream resumes after a pause, state the premises the current line of work depends on, identify for each whether it has been verified against an artifact or inherited from the project record, and name for each what observation would show it to be wrong.\n10. treat every new scientific mechanism",
    "9. on request, and at the point where a result becomes a principal claim or a workstream resumes after a pause, state the premises the current line of work depends on, identify for each whether it has been verified against an artifact or inherited from the project record, and name for each what observation would show it to be wrong;\n10. treat every new scientific mechanism",
)

skill_old = """3. **REFERENCE-VALIDATION.** Enter a proposed reference as Provisional. Check an authoritative source for bibliographic identity and support for the assigned claim. Obtain another participant's check and record uncertainties. The User determines acceptance. A resolved identifier or successful build alone is not validation.\n"""
skill_new = """3. **REFERENCE-VALIDATION.** Enter a proposed reference as Provisional. Check an authoritative source for bibliographic identity and support for the assigned claim. Obtain another participant's check and record uncertainties. The User determines acceptance. A resolved identifier or successful build alone is not validation. Cite empirical, theoretical, methodological, mechanistic, interpretive, and externally sourced quantitative scientific claims. Do not exempt a claim merely because it is described as common knowledge, standard, or well known. Current-project hypotheses, assumptions, derivations, and results need no external citation only for content that genuinely originates in the present work; external premises still require citation. Novelty or priority statements also require the applicable `PRIOR-ART-LINEAGE` search. When uncertain whether an external scientific statement requires citation, cite and validate rather than invoke common knowledge.\n"""
replace_once("skills/scuter/SKILL.md", skill_old, skill_new)

guide_old = """Read and adapt the [work contract](../protocol/01.work-contract.md). Its S8 template records project-specific roles, locations, scope, evidence classes, acceptance criteria, and release requirements. Select a prior-art search coverage declaration and record it. Maintain the search record separately from the claim-specific citation ledger.\n"""
guide_new = """Read and adapt the [work contract](../protocol/01.work-contract.md). Its S8 template records project-specific roles, locations, scope, evidence classes, acceptance criteria, and release requirements. Select a prior-art search coverage declaration and record it. Maintain the search record separately from the claim-specific citation ledger. Apply the protocol's citation requirements when drafting or reviewing scientific text: outside empirical, theoretical, methodological, mechanistic, interpretive, and quantitative claims are cited; describing a claim as common knowledge or standard is not an exemption. Current-project hypotheses, assumptions, derivations, and results are citation-exempt only to the extent they genuinely originate in the present work.\n"""
replace_once("docs/implementation-guide.md", guide_old, guide_new)

review_old = """State the revision inspected, tests and sources examined, observations supported, uncertainties, and necessary repairs. Criticism concerns the artifact, evidence, assumption, or method. The User resolves competing interpretations and determines acceptance.\n"""
review_new = """State the revision inspected, tests and sources examined, observations supported, uncertainties, and necessary repairs. Review scientific prose for uncited external claims as well as for incorrect citations. Do not accept \"common knowledge,\" \"standard,\" or \"well known\" as a citation exemption when a claim is empirical, theoretical, methodological, mechanistic, interpretive, quantitative, or has a plausible alternate convention, scope, interpretation, or domain of validity. Current-project statements are citation-exempt only where they genuinely originate in the present work; external premises remain citable. Novelty and priority statements require the applicable prior-art search in addition to citations. Criticism concerns the artifact, evidence, assumption, or method. The User resolves competing interpretations and determines acceptance.\n"""
replace_once("docs/record-and-review.md", review_old, review_new)

print("Citation requirement source updates applied")
