#!/usr/bin/env python3
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def replace_once(path, old, new):
    p = ROOT / path
    text = p.read_text()
    count = text.count(old)
    if count != 1:
        raise RuntimeError(f"Expected exactly one match in {path}, found {count}")
    p.write_text(text.replace(old, new, 1))


# Protocol: prior-art screening distinction.
old = "3. Abstracts are used to screen results for relevance to the proposition.\n"
new = "3. Abstracts are used to screen results for relevance to the proposition. An abstract is source text, but inspection of an abstract is not represented as inspection of the full paper. If only the abstract is accessible, record the source as abstract-only and limit any support claim to what is explicitly stated there.\n"
replace_once("protocol/01.work-contract.md", old, new)

# Protocol: source-text gate before reference admission workflow.
old = "For this directive, the unit of work is the reference; the output is a citation ledger entry.\n\nSupporting references are admitted with the following protocol:\n"
new = "For this directive, the unit of work is the reference; the output is a citation ledger entry.\n\n### Source-text inspection gate\n\nBefore using a reference as support, the acting participant asks: **Am I getting this information from the actual text of the cited source that I inspected, or from memory?** Claim support is established from the cited source text, not from model memory. Model memory may suggest search terms, authors, titles, or candidate references, but it is only a lead to verify and is never evidence that a source exists or supports a claim.\n\nFor a paper, the preferred basis is the actual primary source text of the paper being cited. For an authoritative non-paper source, inspect the actual authoritative source text. Search-result snippets, generated summaries, another paper's description of the source, secondary citation chains, bibliographic metadata alone, and remembered content do not establish claim-source correspondence. If only an abstract is inspected, record that limitation and support only statements explicitly present in the abstract; do not imply that the full paper was inspected. If the relevant source text cannot be accessed, record the source as inaccessible or unverified rather than describing its contents from memory.\n\nSupporting references are admitted with the following protocol:\n"
replace_once("protocol/01.work-contract.md", old, new)

# Skill: make source-text gate visible at entry level.
old = "3. **REFERENCE-VALIDATION.** Enter a proposed reference as Provisional. Check an authoritative source for bibliographic identity and support for the assigned claim. Obtain another participant's check and record uncertainties. The User determines acceptance. A resolved identifier or successful build alone is not validation. Cite empirical, theoretical, methodological, mechanistic, interpretive, and externally sourced quantitative scientific claims. Do not exempt a claim merely because it is described as common knowledge, standard, or well known. Current-project hypotheses, assumptions, derivations, and results need no external citation only for content that genuinely originates in the present work; external premises still require citation. Novelty or priority statements also require the applicable `PRIOR-ART-LINEAGE` search. When uncertain whether an external scientific statement requires citation, cite and validate rather than invoke common knowledge.\n"
new = "3. **REFERENCE-VALIDATION.** Before using a citation, ask: **Am I getting this information from the actual cited source text I inspected, or from memory?** Memory may suggest a candidate source but never establishes what it says. Inspect the actual paper or authoritative source text for claim support; search snippets, generated summaries, secondary descriptions, citation chains, and bibliographic metadata alone are not sufficient. If only an abstract is inspected, record that fact and support only claims explicitly stated there. If the relevant source text is inaccessible, record it as inaccessible or unverified rather than describing it from memory. Enter a proposed reference as Provisional. Check an authoritative source for bibliographic identity and support for the assigned claim. Obtain another participant's check and record uncertainties. The User determines acceptance. A resolved identifier or successful build alone is not validation. Cite empirical, theoretical, methodological, mechanistic, interpretive, and externally sourced quantitative scientific claims. Do not exempt a claim merely because it is described as common knowledge, standard, or well known. Current-project hypotheses, assumptions, derivations, and results need no external citation only for content that genuinely originates in the present work; external premises still require citation. Novelty or priority statements also require the applicable `PRIOR-ART-LINEAGE` search. When uncertain whether an external scientific statement requires citation, cite and validate rather than invoke common knowledge.\n"
replace_once("skills/scuter/SKILL.md", old, new)

# Implementation guide: operational citation practice.
old = "Read and adapt the [work contract](../protocol/01.work-contract.md). Its S8 template records project-specific roles, locations, scope, evidence classes, acceptance criteria, and release requirements. Select a prior-art search coverage declaration and record it. Maintain the search record separately from the claim-specific citation ledger. Apply the protocol's citation requirements when drafting or reviewing scientific text: outside empirical, theoretical, methodological, mechanistic, interpretive, and quantitative claims are cited; describing a claim as common knowledge or standard is not an exemption. Current-project hypotheses, assumptions, derivations, and results are citation-exempt only to the extent they genuinely originate in the present work.\n"
new = "Read and adapt the [work contract](../protocol/01.work-contract.md). Its S8 template records project-specific roles, locations, scope, evidence classes, acceptance criteria, and release requirements. Select a prior-art search coverage declaration and record it. Maintain the search record separately from the claim-specific citation ledger. Apply the protocol's citation requirements when drafting or reviewing scientific text: outside empirical, theoretical, methodological, mechanistic, interpretive, and quantitative claims are cited; describing a claim as common knowledge or standard is not an exemption. Current-project hypotheses, assumptions, derivations, and results are citation-exempt only to the extent they genuinely originate in the present work.\n\nBefore relying on any citation, ask whether the statement about that source comes from the actual source text inspected in the current work or from memory. Memory may identify a candidate but is not evidence. Inspect the actual paper or authoritative source text before asserting claim support. Do not substitute search snippets, generated summaries, another source's paraphrase, or a citation chain for the cited source. If only an abstract was inspected, say so and limit support to what the abstract explicitly states. If the relevant text cannot be accessed, record the source as inaccessible or unverified rather than reconstructing its contents from memory.\n"
replace_once("docs/implementation-guide.md", old, new)

# Record/review guide: reviewers enforce source inspection provenance.
old = "State the revision inspected, tests and sources examined, observations supported, uncertainties, and necessary repairs. Review scientific prose for uncited external claims as well as for incorrect citations. Do not accept \"common knowledge,\" \"standard,\" or \"well known\" as a citation exemption when a claim is empirical, theoretical, methodological, mechanistic, interpretive, quantitative, or has a plausible alternate convention, scope, interpretation, or domain of validity. Current-project statements are citation-exempt only where they genuinely originate in the present work; external premises remain citable. Novelty and priority statements require the applicable prior-art search in addition to citations. Criticism concerns the artifact, evidence, assumption, or method. The User resolves competing interpretations and determines acceptance.\n"
new = "State the revision inspected, tests and sources examined, observations supported, uncertainties, and necessary repairs. For each material citation, distinguish source text actually inspected from information recalled from memory or inherited from another source. A reviewer does not approve claim-source correspondence based on model memory, search snippets, generated summaries, secondary descriptions, citation chains, or bibliographic metadata alone. If only an abstract was inspected, the record says abstract-only and support is limited to what the abstract explicitly states. Inaccessible source text remains inaccessible or unverified rather than being reconstructed from memory. Review scientific prose for uncited external claims as well as for incorrect citations. Do not accept \"common knowledge,\" \"standard,\" or \"well known\" as a citation exemption when a claim is empirical, theoretical, methodological, mechanistic, interpretive, quantitative, or has a plausible alternate convention, scope, interpretation, or domain of validity. Current-project statements are citation-exempt only where they genuinely originate in the present work; external premises remain citable. Novelty and priority statements require the applicable prior-art search in addition to citations. Criticism concerns the artifact, evidence, assumption, or method. The User resolves competing interpretations and determines acceptance.\n"
replace_once("docs/record-and-review.md", old, new)

print("Applied source-text citation gate")
