from pathlib import Path


def edit(path, replacements):
    p = Path(path)
    text = p.read_text()
    for label, old, new in replacements:
        n = text.count(old)
        if n != 1:
            raise SystemExit(f"{path} / {label}: expected 1 match, found {n}")
        text = text.replace(old, new, 1)
    p.write_text(text)


edit("protocol/01.work-contract.md", [
    ("source-version pin",
     "The existing Citation Validation Ledger is **source-centric at the top level and proposition-centric at the evidence level**. Use one source record per primary work. The source record identifies the canonical citation key or identifier, a concise human-readable source identity such as title and year, the exact complete-primary-text location that was inspected, complete-text access and inspection state, who inspected it, and the inspection date. A DOI or bibliographic URL identifies a work; it is not a substitute for recording the actual full-text artifact or location that was inspected.",
     "The existing Citation Validation Ledger is **source-centric at the top level and proposition-centric at the evidence level**. Use one source record per primary work. The source record identifies the canonical citation key or identifier, a concise human-readable source identity such as title and year, the exact complete-primary-text artifact that was inspected, the source version or edition, an immutable version identifier or content digest that pins the inspected bytes or release, complete-text access and inspection state, who inspected it, and the inspection date. A DOI or bibliographic URL identifies a work; it is not a substitute for recording the actual full-text artifact or version that was inspected. A page, equation, table, figure, section, or supplement locator is interpreted only against that pinned source version. If the available presentation is mutable and no immutable version or digest can be recorded, the participant asks the User for a preservable primary-text version; until the source is pinned, the claim mapping cannot receive `Validated support`. A digest establishes artifact identity, not scientific correctness."),
    ("claim control object",
     "Within each source record, maintain a **claim-evidence mapping table** with one mapping for each exact project or manuscript proposition supported by that source. Each mapping records the claim ID, exact proposition, project or manuscript location, precise evidence locator such as page, section, equation, table, figure, or supplementary item, a concise paraphrase of what the primary source establishes, any scope restriction or caveat, validator and date, second-participant check, User disposition, and mapping status.",
     "Within each source record, maintain a **claim-evidence mapping table** with one mapping for each exact project or manuscript proposition supported by that source. Each mapping records the stable Claim ID, original proposition, current proposition, project or manuscript location, Claim Control Object revision and digest, pinned source-version identity, precise evidence locator such as page, section, equation, table, figure, or supplementary item, a concise paraphrase of what the primary source establishes, any scope restriction or caveat, validator and date, second-participant check, User disposition, and mapping status.\n\nFor manuscript-linked claims, maintain a versioned **Claim Control Object** in a versioned project location. The control object is keyed by stable Claim ID and records at least the current proposition, manuscript file or artifact, stable manuscript anchor, citation mapping, and claim lineage. Each governing version is identified by repository revision or equivalent version identifier and a cryptographic digest such as SHA-256. Citation-ledger mappings reference both the Claim ID and the exact control-object revision/digest. Paragraph numbers, page numbers, line numbers, or other layout-dependent manuscript locations may be recorded for convenience but are not claim identity. Citation-only edits, moved text, narrowed wording, or other claim-relevant changes update the control object so that the change appears in the version/diff chain."),
    ("stable claim narrowing",
     "**Validation is not a source-wide property.** Obtaining or inspecting the complete text does not validate any claim by itself, and validating one source-claim mapping does not validate other claims that cite the same source. If one source supports several propositions, retain one source record and multiple claim-evidence mappings within it. If the evidence supports only a narrower proposition, record the narrower supported formulation and do not promote the broader claim.",
     "**Validation is not a source-wide property.** Obtaining or inspecting the complete text does not validate any claim by itself, and validating one source-claim mapping does not validate other claims that cite the same source. If one source supports several propositions, retain one source record and multiple claim-evidence mappings within it. If review narrows a proposition without changing its scientific identity, preserve the stable Claim ID and record both the original proposition and the narrowed current proposition, with the reason, date, and User disposition; never overwrite the earlier wording. If a claim is split, create child Claim IDs that retain lineage to the parent. If the scientific proposition is materially replaced rather than narrowed, assign a new Claim ID. A narrower supported proposition does not promote the original broader wording."),
    ("validated support independent",
     "Recommended mapping states are `Provisional`, `Validated support`, `Supports narrower formulation`, `Does not support`, and `Needs review`. `Validated support` applies only after the complete primary text has been inspected, the required second check has been recorded, and the User accepts the source as sufficient support for that exact proposition.",
     "Recommended mapping states are `Provisional`, `Validated support`, `Supports narrower formulation`, `Does not support`, and `Needs review`. `Validated support` applies only after the pinned complete primary text has been inspected, the required prospectively blinded second check has been recorded, and the User accepts the source as sufficient support for that exact proposition."),
    ("validation steps",
     "2. The acting participant obtains and inspects the complete primary text, confirms source identity, and records the canonical citation key or identifier, concise source identity, exact complete-text location inspected, inspector, and inspection date.\n3. For each manuscript or project proposition that will cite the source, the participant creates or updates a separate claim-evidence mapping with the exact proposition, project location, evidence locator, evidence note, and scope or caveat. Bibliographic identity or source-level inspection alone is not claim validation.\n4. A second-participant check evaluates the complete primary text and the specific claim-evidence mapping. Disagreements, corrections, narrower support, and uncertainties are recorded. This check is designated independent only where exposure was prospectively controlled and recorded; otherwise it is recorded as a second check following exposure.\n5. The User determines whether the evidence is sufficient for each exact source-claim mapping. Only an accepted mapping may receive `Validated support`; another claim citing the same source remains separately unresolved until its own mapping is validated.",
     "2. The acting participant obtains and inspects the complete primary text, confirms source identity, and records the canonical citation key or identifier, concise source identity, exact complete-text artifact inspected, source version or edition, immutable version identifier or content digest, inspector, and inspection date.\n3. For each manuscript or project proposition that will cite the source, the participant creates or updates a separate claim-evidence mapping with the stable Claim ID, original and current proposition as applicable, Claim Control Object revision/digest, pinned source-version identity, evidence locator, evidence note, and scope or caveat. Bibliographic identity or source-level inspection alone is not claim validation.\n4. The required second-participant check is **prospectively blinded by construction**. The reviewer receives the source identity or pinned source artifact and the exact Claim ID/proposition to test, but does not read the first validator's evidence locator, evidence note, caveat, or disposition before completing their own primary-text inspection. The reviewer independently records their own locator, paraphrase, caveat, and disposition in a durable record before exposure to the first assessment. Only then are the two assessments compared and discrepancies reconciled. If prior exposure cannot be excluded, record a useful second check following exposure, but do not call it independent and do not use it to satisfy the independent second-check requirement for `Validated support`.\n5. The User determines whether the evidence is sufficient for each exact source-claim mapping after the two assessments are available. Only an accepted mapping that satisfies the independent second-check requirement may receive `Validated support`; another claim citing the same source remains separately unresolved until its own mapping is validated."),
    ("durable ledger property source pin",
     "3. **Record the complete text actually inspected.** A DOI or landing page identifies a source but does not prove complete-text access. Record the URL, uploaded PDF, repository file, or other exact full-text artifact used for validation, together with inspection provenance.\n4. **Validation belongs to the source-claim mapping.** Each mapping identifies the exact project or manuscript proposition, evidence locator, concise evidence note, scope or caveat, validator, second check, and User disposition. A source-level access or inspection field must never imply that all claims attached to that source are validated.",
     "3. **Record and pin the complete text actually inspected.** A DOI or landing page identifies a source but does not prove complete-text access or version identity. Record the URL, uploaded PDF, repository file, or other exact full-text artifact used for validation, plus source version or edition and an immutable version identifier or content digest. Evidence locators are valid only for that pinned version.\n4. **Validation belongs to the source-claim mapping.** Each mapping identifies the stable Claim ID, original and current proposition where wording has changed, Claim Control Object revision/digest, pinned source version, evidence locator, concise evidence note, scope or caveat, validator, prospectively blinded second check, and User disposition. A source-level access or inspection field must never imply that all claims attached to that source are validated."),
])

edit("skills/scuter/SKILL.md", [
    ("citation audit section",
     "The User defines the evidentiary threshold and is the only participant who promotes a proposition into evidence-supported project state. AI participants may identify evidence and recommend promotion, but never silently remove a hypothesis-only label or broaden an evidence-supported statement beyond the proposition the User accepted. Preserve the prior hypothesis state and the User's promotion decision in the durable record.\n\n## Start a project",
     "The User defines the evidentiary threshold and is the only participant who promotes a proposition into evidence-supported project state. AI participants may identify evidence and recommend promotion, but never silently remove a hypothesis-only label or broaden an evidence-supported statement beyond the proposition the User accepted. Preserve the prior hypothesis state and the User's promotion decision in the durable record.\n\n## Citation-audit discipline\n\nPin every evidence locator to the exact primary-source version inspected. Record the source version or edition and an immutable version identifier or content digest; page, equation, table, figure, section, or supplement numbering without that pin is not sufficient. A digest identifies bytes or a release and does not itself validate scientific content.\n\nKeep a stable Claim ID across wording that is narrowed without changing the claim's scientific identity. Preserve both original and current wording, the reason/date of narrowing, and the User disposition. A split claim receives child IDs with lineage; a materially different replacement receives a new Claim ID. For manuscript-linked claims, anchor the Claim ID in a versioned Claim Control Object that records the proposition, manuscript file/anchor, citation mapping, repository revision or equivalent version, and a cryptographic digest. Claim-evidence mappings reference the Claim ID plus the exact control-object revision/digest so citation-only and wording edits remain in the same diff chain.\n\nPerform the required citation second check prospectively blinded by construction. Give the second participant the pinned primary source and exact Claim ID/proposition, but withhold the first validator's evidence locator, support note, caveat, and disposition until the reviewer has durably recorded their own locator, paraphrase, caveat, and disposition from the primary text. Only then compare assessments. If prior exposure occurred, label the result as a second check following exposure rather than independent; it does not satisfy the independent second-check requirement for `Validated support`.\n\n## Start a project"),
])

edit("docs/notion-setup.md", [
    ("source fields",
     "| Complete primary text | Files, URL, or text | Exact uploaded PDF, full-text URL, repository path, or other artifact actually inspected |\n| Complete text status | Select | `Obtained`, `Needs full text`, or `Not yet checked` |\n| Complete text inspected | Checkbox | Whether the complete primary text has actually been inspected |",
     "| Complete primary text | Files, URL, or text | Exact uploaded PDF, full-text URL, repository path, or other artifact actually inspected |\n| Source version / edition | Text | Publication version, edition, release, or other human-readable version identity |\n| Source version pin | Text | Immutable version identifier or content digest for the exact text inspected |\n| Complete text status | Select | `Obtained`, `Needs full text`, or `Not yet checked` |\n| Complete text inspected | Checkbox | Whether the pinned complete primary text has actually been inspected |"),
    ("mapping table",
     "| Claim ID | Exact project/manuscript proposition | Project/manuscript location | Evidence location | Evidence note | Scope/caveat | Validator/date | Second check | User acceptance | Mapping status |\n| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |\n| `INTRO-03` | Exact proposition being cited | `Main Intro P2` | p. 7, Fig. 2 | Short paraphrase of what the complete primary text establishes | Any narrower scope or limitation | participant + date | reviewer + disposition | accepted / not accepted / pending | `Validated support`, `Supports narrower formulation`, `Does not support`, `Needs review`, or `Provisional` |\n\n`Validated support` is claim-specific. It is used only after complete-primary-text inspection, the required second check, and User acceptance for that exact proposition. If the same source is cited for another proposition, add another mapping row and validate it separately. If the evidence supports only a narrower formulation, record the narrower wording rather than validating the broader claim.",
     "| Claim ID | Original proposition | Current proposition | Claim Control Object revision / digest | Source version pin | Evidence location | Evidence note | Scope/caveat | Validator/date | Blinded second check/date | User acceptance | Mapping status |\n| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |\n| `INTRO-03` | Original proposition first audited | Current or narrowed proposition | repository revision + digest | source version / digest | p. 7, Fig. 2 | Short paraphrase of what the pinned complete primary text establishes | Any narrower scope or limitation | participant + date | reviewer + independent locator/disposition + date | accepted / not accepted / pending | `Validated support`, `Supports narrower formulation`, `Does not support`, `Needs review`, or `Provisional` |\n\nThe `Current proposition` field is the **Exact project/manuscript proposition** being validated for that mapping. `Validated support` is claim-specific. It is used only after inspection of the pinned complete primary text, a prospectively blinded second check, and User acceptance for that exact proposition. The second reviewer receives the exact Claim ID/proposition and pinned source but does not see the first validator's locator, evidence note, caveat, or disposition before recording their own assessment. If the same source is cited for another proposition, add another mapping row and validate it separately.\n\nUse a stable Claim ID when review narrows wording without changing the scientific identity of the claim. Preserve **original and current wording** rather than overwriting history, including the original proposition and current narrowed proposition. If one claim splits, create child Claim IDs with lineage to the parent; if the proposition is materially replaced, create a new Claim ID.\n\nFor manuscript-linked claims, keep a versioned **Claim Control Object** in the manuscript or project repository. It maps Claim IDs to current proposition text, manuscript file and stable anchor, citation mapping, and claim lineage, and records a repository revision or equivalent version plus a cryptographic digest such as SHA-256. Ledger mappings point to the exact control-object revision/digest. Paragraph/page/line positions can be convenience locators, but the Claim ID plus control-object version is the durable manuscript anchor. Citation-only edits and narrowed wording update the control object and therefore remain visible in the version/diff chain."),
])

edit("docs/implementation-guide.md", [
    ("ledger audit additions",
     "Maintain one source record per primary work in the existing Citation Validation Ledger. Record source identity, the exact complete-text artifact or location inspected, access and inspection state, inspector, and date at the source level. Inside that source record, maintain one claim-evidence mapping for each exact project or manuscript proposition that cites the work. Each mapping records the exact proposition, manuscript or project location, evidence locator, concise support note, scope or caveat, validator and date, second check, User disposition, and mapping status. A paper is never \"validated\" in the abstract: validation applies to a specific source-claim mapping. One validated mapping does not confer validation on another claim citing the same paper.",
     "Maintain one source record per primary work in the existing Citation Validation Ledger. Record source identity, the exact complete-text artifact inspected, source version or edition, immutable version identifier or content digest, access and inspection state, inspector, and date at the source level. Evidence locators are interpreted only against that pinned source version. Inside that source record, maintain one claim-evidence mapping for each exact project or manuscript proposition that cites the work. Each mapping records the stable Claim ID, original and current proposition where applicable, Claim Control Object revision/digest, source version pin, evidence locator, concise support note, scope or caveat, validator and date, blinded second check, User disposition, and mapping status. A paper is never \"validated\" in the abstract: validation applies to a specific source-claim mapping. One validated mapping does not confer validation on another claim citing the same paper.\n\nFor the citation second check, expose the reviewer to the exact Claim ID/proposition and pinned primary source, but not the first validator's locator, evidence note, caveat, or disposition. The reviewer first records an independent locator, paraphrase, caveat, and disposition from the complete primary text; only then compare the two assessments. Record any earlier exposure explicitly and do not label an exposed check independent.\n\nFor manuscript-linked claims, maintain a versioned Claim Control Object keyed by stable Claim ID. It records the current proposition, manuscript file and stable anchor, citation mapping, and claim lineage together with a repository revision or equivalent version and cryptographic digest. When audit narrows wording, retain the same Claim ID if the scientific identity is preserved and store both original and current wording. Citation-only edits, moved text, and narrowed wording update the control object so they remain visible in the same version/diff chain."),
])

edit("docs/record-and-review.md", [
    ("review mapping discipline",
     "Validate citations at the **source-claim mapping** level. The Citation Validation Ledger keeps one source record per primary work, but every exact manuscript or project proposition has its own evidence locator, support note, scope or caveat, checks, and User disposition. Do not infer support for one proposition from a different validated mapping to the same paper, and do not treat complete-text access or inspection as source-wide scientific validation. Reviewers should be able to recover the exact supporting passage or element from the recorded locator without reconstructing the claim from memory.",
     "Validate citations at the **source-claim mapping** level. The Citation Validation Ledger keeps one source record per primary work, but every exact manuscript or project proposition has its own stable Claim ID, pinned source version, evidence locator, support note, scope or caveat, checks, and User disposition. Pin every locator to the exact complete-primary-text version inspected using an immutable version identifier or content digest. Do not infer support for one proposition from a different validated mapping to the same paper, and do not treat complete-text access or inspection as source-wide scientific validation. Reviewers should be able to recover the exact supporting passage or element from the recorded locator and pinned source without reconstructing the claim from memory.\n\nThe citation second check is prospectively blinded. Before seeing the first validator's locator, evidence note, caveat, or disposition, the second participant receives the exact Claim ID/proposition and pinned source, inspects the primary text independently, and durably records their own locator, paraphrase, caveat, and disposition. Then compare the two assessments. If exposure occurred first, record a second check following exposure rather than independent confirmation.\n\nWhen review narrows a claim, preserve its stable Claim ID if its scientific identity remains the same and record both original and current wording, the reason/date, and User disposition. Use child IDs for a split claim and a new ID for a materially different replacement. For manuscript-linked claims, reference a versioned Claim Control Object revision/digest rather than relying on mutable paragraph or page positions; citation-only and wording changes update that control object and remain in the artifact diff chain."),
])

p = Path("tests/test_citation_ledger_contract.py")
text = p.read_text()
anchor = "        self.assertIn(\"Source-level access or support for one proposition never validates other claims\", text)\n"
addition = anchor + "\n    def test_version_pinning_blinding_and_claim_control_are_required(self):\n        protocol = (ROOT / \"protocol/01.work-contract.md\").read_text()\n        notion = (ROOT / \"docs/notion-setup.md\").read_text()\n        skill = (ROOT / \"skills/scuter/SKILL.md\").read_text()\n        review = (ROOT / \"docs/record-and-review.md\").read_text()\n        for text in (protocol, notion, skill, review):\n            self.assertIn(\"Claim Control Object\", text)\n            self.assertIn(\"stable Claim ID\", text)\n        self.assertIn(\"content digest\", protocol)\n        self.assertIn(\"prospectively blinded by construction\", protocol)\n        self.assertIn(\"Blinded second check/date\", notion)\n        self.assertIn(\"original and current wording\", notion)\n        self.assertIn(\"does not satisfy the independent second-check requirement\", skill)\n"
if text.count(anchor) != 1:
    raise SystemExit(f"test anchor: expected 1 match, found {text.count(anchor)}")
p.write_text(text.replace(anchor, addition, 1))
