#!/usr/bin/env python3
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def replace_once(path, old, new):
    p = ROOT / path
    text = p.read_text()
    count = text.count(old)
    if count != 1:
        raise RuntimeError(f"Expected exactly one match in {path}, found {count}")
    p.write_text(text.replace(old, new, 1))

# Protocol: abstracts can screen prior art but cannot validate a citation.
replace_once(
    "protocol/01.work-contract.md",
    "3. Abstracts are used to screen results for relevance to the proposition. An abstract is source text, but inspection of an abstract is not represented as inspection of the full paper. If only the abstract is accessible, record the source as abstract-only and limit any support claim to what is explicitly stated there.\n",
    "3. Abstracts may be used to screen results for relevance to the proposition, but an abstract alone cannot validate a citation or establish claim support. A retained candidate proceeds to `REFERENCE-VALIDATION` only after the complete primary text is obtained and inspected.\n",
)

old_gate = """### Source-text inspection gate

Before using a reference as support, the acting participant asks: **Am I getting this information from the actual text of the cited source that I inspected, or from memory?** Claim support is established from the cited source text, not from model memory. Model memory may suggest search terms, authors, titles, or candidate references, but it is only a lead to verify and is never evidence that a source exists or supports a claim.

For a paper, the preferred basis is the actual primary source text of the paper being cited. For an authoritative non-paper source, inspect the actual authoritative source text. Search-result snippets, generated summaries, another paper's description of the source, secondary citation chains, bibliographic metadata alone, and remembered content do not establish claim-source correspondence. If only an abstract is inspected, record that limitation and support only statements explicitly present in the abstract; do not imply that the full paper was inspected. If the relevant source text cannot be accessed, record the source as inaccessible or unverified rather than describing its contents from memory.
"""
new_gate = """### Complete-primary-text requirement

**All citations must be sourced from the complete primary text of the cited work.** Claim-source correspondence is established only from primary text that the acting participant has actually inspected. Model memory may suggest search terms, authors, titles, or candidate references, but memory is never evidence that a source exists or supports a claim.

For a paper, inspect the complete paper rather than relying on the abstract. For another citable primary source, inspect the complete primary source needed to evaluate the cited claim. Abstracts, search-result snippets, generated summaries, another paper's description, secondary citation chains, bibliographic metadata, and remembered content may help locate or screen a source but cannot validate it or support a manuscript claim.

If the acting participant cannot access the complete primary text, citation validation stops. The participant asks the User to provide the complete primary text or access to it. Obtaining and supplying the source material needed for review is the User's responsibility as project leader. Until the complete primary text is available and inspected, the reference remains Provisional, inaccessible, or unverified and cannot be used as evidentiary support for a project claim.
"""
replace_once("protocol/01.work-contract.md", old_gate, new_gate)

# Skill directive: statement, not question; complete primary text required.
old = "3. **REFERENCE-VALIDATION.** Before using a citation, ask: **Am I getting this information from the actual cited source text I inspected, or from memory?** Memory may suggest a candidate source but never establishes what it says. Inspect the actual paper or authoritative source text for claim support; search snippets, generated summaries, secondary descriptions, citation chains, and bibliographic metadata alone are not sufficient. If only an abstract is inspected, record that fact and support only claims explicitly stated there. If the relevant source text is inaccessible, record it as inaccessible or unverified rather than describing it from memory. Enter a proposed reference as Provisional. Check an authoritative source for bibliographic identity and support for the assigned claim. Obtain another participant's check and record uncertainties. The User determines acceptance. A resolved identifier or successful build alone is not validation. Cite empirical, theoretical, methodological, mechanistic, interpretive, and externally sourced quantitative scientific claims. Do not exempt a claim merely because it is described as common knowledge, standard, or well known. Current-project hypotheses, assumptions, derivations, and results need no external citation only for content that genuinely originates in the present work; external premises still require citation. Novelty or priority statements also require the applicable `PRIOR-ART-LINEAGE` search. When uncertain whether an external scientific statement requires citation, cite and validate rather than invoke common knowledge.\n"
new = "3. **REFERENCE-VALIDATION.** **All citations must be sourced from the complete primary text of the cited work.** Memory may suggest a candidate source but never establishes what it says. Abstracts, search snippets, generated summaries, secondary descriptions, citation chains, and bibliographic metadata may help locate or screen a source but cannot validate it or support a project claim. Inspect the complete paper or other complete primary source needed to evaluate the cited claim. If the complete primary text is unavailable, stop validation and ask the User to provide the text or access to it; obtaining the source material needed for review is the User's responsibility as project leader. Until then, the reference remains Provisional, inaccessible, or unverified and cannot support a project claim. Enter a proposed reference as Provisional. Check an authoritative source for bibliographic identity and support for the assigned claim. Obtain another participant's check and record uncertainties. The User determines acceptance. A resolved identifier or successful build alone is not validation. Cite empirical, theoretical, methodological, mechanistic, interpretive, and externally sourced quantitative scientific claims. Do not exempt a claim merely because it is described as common knowledge, standard, or well known. Current-project hypotheses, assumptions, derivations, and results need no external citation only for content that genuinely originates in the present work; external premises still require citation. Novelty or priority statements also require the applicable `PRIOR-ART-LINEAGE` search. When uncertain whether an external scientific statement requires citation, cite and validate rather than invoke common knowledge.\n"
replace_once("skills/scuter/SKILL.md", old, new)

# Implementation guide.
old = "Before relying on any citation, ask whether the statement about that source comes from the actual source text inspected in the current work or from memory. Memory may identify a candidate but is not evidence. Inspect the actual paper or authoritative source text before asserting claim support. Do not substitute search snippets, generated summaries, another source's paraphrase, or a citation chain for the cited source. If only an abstract was inspected, say so and limit support to what the abstract explicitly states. If the relevant text cannot be accessed, record the source as inaccessible or unverified rather than reconstructing its contents from memory.\n"
new = "All citations are sourced from the complete primary text of the cited work. Memory may identify a candidate but is not evidence. Abstracts, search snippets, generated summaries, another source's paraphrase, citation chains, and bibliographic metadata may be used for discovery or screening but not for citation validation or claim support. Inspect the complete paper or other complete primary source needed to evaluate the cited claim. If the complete primary text cannot be accessed, stop validation and ask the User to provide the text or access to it. Obtaining the source material needed for review is the User's responsibility as project leader. Until supplied and inspected, the reference remains Provisional, inaccessible, or unverified and cannot support a project claim.\n"
replace_once("docs/implementation-guide.md", old, new)

# Review guide.
old = "State the revision inspected, tests and sources examined, observations supported, uncertainties, and necessary repairs. For each material citation, distinguish source text actually inspected from information recalled from memory or inherited from another source. A reviewer does not approve claim-source correspondence based on model memory, search snippets, generated summaries, secondary descriptions, citation chains, or bibliographic metadata alone. If only an abstract was inspected, the record says abstract-only and support is limited to what the abstract explicitly states. Inaccessible source text remains inaccessible or unverified rather than being reconstructed from memory. Review scientific prose for uncited external claims as well as for incorrect citations. Do not accept \"common knowledge,\" \"standard,\" or \"well known\" as a citation exemption when a claim is empirical, theoretical, methodological, mechanistic, interpretive, quantitative, or has a plausible alternate convention, scope, interpretation, or domain of validity. Current-project statements are citation-exempt only where they genuinely originate in the present work; external premises remain citable. Novelty and priority statements require the applicable prior-art search in addition to citations. Criticism concerns the artifact, evidence, assumption, or method. The User resolves competing interpretations and determines acceptance.\n"
new = "State the revision inspected, tests and sources examined, observations supported, uncertainties, and necessary repairs. A reviewer approves claim-source correspondence only after inspecting the complete primary text of the cited work. Model memory, abstracts, search snippets, generated summaries, secondary descriptions, citation chains, and bibliographic metadata may assist discovery or screening but cannot validate a citation or support a project claim. If the complete primary text is unavailable, the reviewer or acting participant asks the User to provide the text or access to it; obtaining the source material needed for review is the User's responsibility as project leader. Until supplied and inspected, the reference remains Provisional, inaccessible, or unverified. Review scientific prose for uncited external claims as well as for incorrect citations. Do not accept \"common knowledge,\" \"standard,\" or \"well known\" as a citation exemption when a claim is empirical, theoretical, methodological, mechanistic, interpretive, quantitative, or has a plausible alternate convention, scope, interpretation, or domain of validity. Current-project statements are citation-exempt only where they genuinely originate in the present work; external premises remain citable. Novelty and priority statements require the applicable prior-art search in addition to citations. Criticism concerns the artifact, evidence, assumption, or method. The User resolves competing interpretations and determines acceptance.\n"
replace_once("docs/record-and-review.md", old, new)

# Notion setup: citation ledger should record source access/inspection basis.
old = "Create a Project Overview, one Collaboration Log, a prior-art search record, and a citation ledger. Add numbered notebooks for longer methods and analyses as needed. The Overview states what currently governs. The log preserves material actions, evidence, decisions, and next steps.\n"
new = "Create a Project Overview, one Collaboration Log, a prior-art search record, and a citation ledger. Add numbered notebooks for longer methods and analyses as needed. The Overview states what currently governs. The log preserves material actions, evidence, decisions, and next steps. The citation ledger records whether the complete primary text was actually inspected for each reference. Abstract-only, snippet-only, memory-based, secondary-source, or inaccessible candidates are not validated citations. If complete primary text is unavailable, the acting participant asks the User to provide the text or access to it before validation continues.\n"
replace_once("docs/notion-setup.md", old, new)

print("Strengthened complete-primary-text citation gate")
